"""
Django settings for task_reminder project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

def get_env(var_name, default=None, required=False):
    """Safely read environment variable."""
    value = os.environ.get(var_name, default)
    if required and not value:
        raise ImproperlyConfigured(f"Environment variable '{var_name}' is required but not set.")
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# On PythonAnywhere, set the DJANGO_SECRET_KEY environment variable.
# Locally, create a .env file (never commit it) or set the variable in your shell.
SECRET_KEY = get_env(
    'DJANGO_SECRET_KEY',
    default='django-insecure-local-dev-key-change-in-production',  # safe placeholder
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DJANGO_DEBUG', default='False') == 'True'

# Add your PythonAnywhere username below (e.g. 'yourusername.pythonanywhere.com')
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.pythonanywhere.com',  # covers all *.pythonanywhere.com subdomains
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project1.context_processors.google_maps_api', # custom context processor
            ],
        },
    },
]

WSGI_APPLICATION = 'project1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: compress and cache static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Config (Gmail SMTP)
# ⚠️  DO NOT hardcode credentials here.
# Set these as environment variables on PythonAnywhere (Web > Environment variables):
#   DJANGO_EMAIL_USER  = your email address
#   DJANGO_EMAIL_PASS  = your Gmail app password
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = get_env('DJANGO_EMAIL_USER', required=True)
EMAIL_HOST_PASSWORD = get_env('DJANGO_EMAIL_PASS', required=True)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Twilio SMS Config
# ⚠️  DO NOT hardcode credentials here.
# Set these as environment variables on PythonAnywhere (Web > Environment variables):
#   TWILIO_ACCOUNT_SID  = your Twilio Account SID (starts with AC...)
#   TWILIO_AUTH_TOKEN   = your Twilio Auth Token
#   TWILIO_PHONE_NUMBER = your Twilio phone number (e.g. +917997182627)
TWILIO_ACCOUNT_SID = get_env('TWILIO_ACCOUNT_SID', required=True)
TWILIO_AUTH_TOKEN = get_env('TWILIO_AUTH_TOKEN', required=True)
TWILIO_PHONE_NUMBER = get_env('TWILIO_PHONE_NUMBER', default='+917997182627')

# Google Maps Config
# Set this as an environment variable on PythonAnywhere:
#   GOOGLE_MAPS_API_KEY = your real key
GOOGLE_MAPS_API_KEY = get_env('GOOGLE_MAPS_API_KEY', default='AIzaSyAIPbgRXzLosqB1vxSWVyfUy2vYflpU3zg')
